
print("    *  * *       * *  *")
print("  *        *   *        *")
print(" *           *           *")
print(" *                       *")
print("  *        I <3 U       *")
print("   *                   *")
print("     *               *")
print("       *           *")
print("         *       *")
print("           *   *")
print("             *")